### ISSUE TITLE
FILTER FEED

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#11]
### FILTER FEED SUMMARY
Filtering lets you discover records in your feed by price range, condition or record type (new, reissue, etc.) preferences. It's a great way to specify the records you'd like to discover to add to your collection. 

### **VIEW REQUIREMENTS**
**Filter by release type**
- [ ] Title "Filter"
- [ ] New, reissue, used switches

**Filter by release condition**
- [ ] Condition slider
- [ ] Condition subtitle

**Filter by price**
- [ ] Price subheader
- [ ] Price range slider 

**Actions**
- [ ] Clear Filter Button
- [ ] Done Button

### **USER STORIES**

_As a buyer, when I'm interested in purchasing records at a certain price or quality, I want to be able to quickly change the types of records I see available for sale so that I can find releases that fall within the specific criteria I'm interested in adding to my collection._

_As a product company, we want to cater to the specific preferences of quality and condition of releases to our customer needs, so we need to provide a range of flexibility for customization so that users can speedily acquire the releases of interest with as little friction as possible. The faster users can buy what they are looking for in the condition or price range they are most interested, the more records we can sell._
