### ISSUE TITLE
USER PROFILE

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#16]
### **PROFILE SUMMARY**
User profiles allow buyers and sellers a means to create shipping, identity, payment preferences. It also gives users an ability to view and edit listings in their archive and access to making them available for sale. 

The scope has been separated by two core experiences that can be accessed through a user's profile.

**Listings:** 
- Archived
- For Sale

**User Settings:** 
- Application Settings
- Profile Settings

### **PROFILE VIEW REQUIREMENTS**

**HEADER**
- [ ] First name
- [ ] User avatar thumbnail
- [ ] City & State (NC)

**BODY**

**SubNavigation**
- [ ] List view of releases for sale
- [ ] List view of listed releases (not for sale)

**List View**
- [ ] Release thumbnail
 - [ ] Artist name
- [ ] Release title 
- [ ] Release price
- [ ] Release condition
- [ ] Status (**Note:** Only applies to listings for sale in the sub tab)
	- [ ] Sold 
	- [ ] For Sale 
	
**Actions**
- [ ] Settings Button (text)

**PROFILE VIEW STORY**
_As a seller, when change my username or edit the records I’ve listed, I want to view the records I’ve listed or those I’m offering for sale, so I can ensure my profile, application settings all reflect accurate information._

_As a buyer, when I want to change my address, I need a way to view my profile so to access my profile settings._

_As a buyer, when I want to see if I record I have already purchased, I want to be able to see those  records within my profile, so I can make a purchasing or selling decision based on my inventory._

_As a buyer who is considering selling, I want quickly make a record within my listings for sale, so I can save time while avoiding making any mistakes by listing it manually (e.g. flip a record for sale within my listings.)_
