### ISSUE TITLE
PRODUCT DEFINITION & SCOPE CHECKLIST

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#18]
# Product Definition and Development Checklist 

## PRODUCT DEFINITION

VNYLST is the fastest way to buy and sell vinyl records that allow for matching records you want to own with vendors nearby.  With VNYLST, you can list records for sale, appraise, and create a digital archive of the records you own, and eventually want to own. 

For questions on how this scope has been developed and documented, please contact Sekoú at admin@vnylst.com. 

## **SCOPE CHECKLIST**
- [x] Loading App & Authentication
- [x] Feed
- [x] Listing for archive (1 of 2 Epics)
- [x] Listing for sale (2 of 2 Epics)
- [x] Messaging List (1 of 2 Epics)
- [x] Messaging Conversation (2 of 2 Epics)
- [x] Filtering
- [ ] Purchasing
- [x] User Profile 
- [x] Release Profile (read only)
- [x] Edit a Release 
- [x] User Settings (1 of 2 Epics)
- [x] Application Settings (2 of 2 Epics)

## **DESIGN CHECKLIST**
- [x] Loading App & Authentication
- [x] Feed
- [x] Listing for archive (1 of 2 Epics)
- [ ] Listing for sale (2 of 2 Epics)
- [x] Messaging List (1 of 2 Epics)
- [x] Messaging Conversation (2 of 2 Epics)
- [x] Filtering
- [x] Purchasing
- [x] User Profile 
- [x] Release Profile (read only)
- [x] Edit a Release 
- [x] User Settings (1 of 2 Epics)
- [x] Application Settings (2 of 2 Epics)

## **PROTOTYPE CHECKLIST**
- [x] Loading App & Authentication
- [x] Feed
- [x] Listing for archive (1 of 2 Epics)
- [ ] Listing for sale (2 of 2 Epics)
- [x] Messaging List (1 of 2 Epics)
- [x] Messaging Conversation (2 of 2 Epics)
- [x] Filtering
- [ ] Purchasing
- [x] User Profile 
- [x] Release Profile (read only)
- [x] Edit a Release 
- [x] User Settings (1 of 2 Epics)
- [x] Application Settings (2 of 2 Epics)

## **DEVELOPMENT CHECKLIST**
- [ ] Loading App & Authentication
- [ ] Feed
- [ ] Listing for archive (1 of 2 Epics)
- [ ] Listing for sale (2 of 2 Epics)
- [ ] Messaging List (1 of 2 Epics)
- [ ] Messaging Conversation (2 of 2 Epics)
- [ ] Filtering
- [ ] Purchasing
- [ ] User Profile 
- [ ] Release Profile (read only)
- [ ] Edit a Release 
- [ ] Settings
