### ISSUE TITLE
LIST A RELEASE

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#2]
### LIST A RELEASE SUMMARY
Listing a release functionality allows buyers and sellers to post or list records on the platform with the mobile application. 

**Note:** a release cannot be listed unless the compulsory input fields are completely filled out.

### LISTING A RELEASE TASKS IN STEPS
1. Capturing a photo. 
2. Adding release details. 
3. Confirming release details.

### LISTING A RELEASE VIEWS AS STEPS
1. IMAGE CAPTURE (CAMERA)
2. LISTING VIEW
3. LISTING CONFIRMATION

### CAPTURE VIEW REQUIREMENTS

**Header**
- [ ] “Album Art” Title

**Body**
- [ ] Image Grid
- [ ] “Photograph Front Cover” Copy

**Action**
- [ ] Capture Image
- [ ] Close View

### IMAGE CAPTURED VIEW REQUIREMENTS
**Header**
- [ ] “Album Art” Title

**Body**
- [ ] Confirmation Copy
- [ ] "✔️ "Confirmation Icon

**Action**
- [ ] Back Button
- [ ] Next Button

### RELEASE LISTING REQUIREMENTS
**Header**
- [ ] Title "Listing"
- [ ] Release details & condition

**Body**
- [ ] Artist name
- [ ] Release title
- [ ] Genre
- [ ] Catalog number
- [ ] Release year
- [ ] Barcode (optional)

**Release Type**
- [ ] New
- [ ] Used
- [ ] Reissue

**Vinyl Condition**
- [ ] Slider  (Good, Very Good, Very Good Plus, Excellent, Mint)
- [ ] Comment (Pre-filled editable input field)

**Sleeve Condition**
- [ ] *Slider  (Good, Very Good, Very Good Plus, Excellent, Mint)
- [ ] Comment (Pre-filled editable input field)

**List for sale** 
- [ ] "Sale this release" title
- [ ] Subtitle: "Buy and sale securely using Paypal to make transactions. Transactions are subject to a 8% fee. Read more **here**."
- [ ] Switch

### **ACTIONS**
- [ ] Cancel
- [ ] Done ✔️ icon

**User Story**
_When I have a record I want to list or sell, I need a way to capture the album artwork, add the release information (artist name, year of release, record label, record genre etc.), list the condition of the record sleeve and the actual record, so that a buyer can make an informed decision before purchasing or contacting me for further information — or — so I can have the information documented so I can sell it at another date — or — so I can have a documented release for my personal archive/collection._

**Product Story**
_In order to ensure we can offer the best records for sale, we (eventually) need a way to qualify and verify sellers based on the authenticity of their inventory, identification and the quality of releases they have for sale. This ensures users' peace of mind, saves time going through filler, and keeps the quality consistent and high caliber._

**Comment by vnylst** [comment]
![list view](https://cloud.githubusercontent.com/assets/13191477/24494962/da261142-155d-11e7-846c-e73c3b02d9a8.png)
