### ISSUE TITLE
RELEASE PROFILE

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#5]
### RELEASE PROFILE VIEW (READY ONLY) SUMMARY
Release profiles give buyers and sellers more information about a release, which aids in their buying or selling decisions.

### **RELEASE PROFILE REQUIREMENTS**
**Header**
- [ ] Artwork
- [ ] Release title
- [ ] Artist name
- [ ] Release year
- [ ] Release price
- [ ] Release condition

**Body**
- [ ] Genre & Style

**Subheader**
- [ ] Record Details
- [ ] Table List

- [ ] Artist name subtitle
- [ ] Artist name

- [ ] Release title subtitle
- [ ] Release name

- [ ] Release year subtitle
- [ ] Release name

- [ ] Catalog number subtitle
- [ ] Catalog number

- [ ] Record condition & comment subtitle
- [ ] Record condition
- [ ] Record condition comments

- [ ] Sleeve condition & comments subtitle
- [ ] Record condition
- [ ] Record condition comments

**Actions**
- [ ] “Buy this release” button. **_Note:_** only when release is listed for sale. 
- [ ] Price
- [ ] Close view

**Buyer User Story**
When I see a record I'd like to know more about, I need a way to view detailed information without having to contact the seller. This is so I can be informed about the release prior to taking action on it.

**Seller User Story**
When I have listed a release (for sale), I want to see it along with the other releases under my profile, so that I can assess my inventory, or even the record details prior to selling or updating the release information.

**Comment by vnylst** [comment]
![profile view](https://cloud.githubusercontent.com/assets/13191477/24493553/67d8ea46-1559-11e7-993b-3da24967b913.png)
