### ISSUE TITLE
APPLICATION SETTINGS (2 OF 3 EPIC)

### ISSUE THREAD

**Issue by vnylst** [vnylst/VNYLST#6]
## APPLICATION SETTINGS SUMMARY

Application settings are where a users discovery and notifications live, giving them access to controlling how they elect to interact with the application.
**Design:** https://invis.io/5CB93EIMD#/226864615_Application_Settings

### APPLICATION SETTINGS REQUIREMENTS

**HEADER**
- [ ] View title  **Application settings**
- [ ] View subtitle **Discovery and notifications preferences**

**BODY**
- [ ] Subnavigation title *Application*
- [ ] Subnavigation title *Profile*

- [ ] Header titled “_DISCOVERY_”
- [ ] Subheader titled “*Discover records nearby or a preferred distance*”
- [ ] Cell Slider (*Note:* 1 mile minimum with a +1,000 mile maximum)

- [ ] Header titled “_NOTIFICATIONS_”
- [ ] Subtitle “_Get notified for finds, messages or new releases_”
- [ ] Cell Switch titled *New Finds*
- [ ] Cell switch titled *Messages*
- [ ] Cell switch titled *New releases*

**ACTIONS**
- [ ] Close view

**Comment by vnylst** [comment]
Invision[link](https://invis.io/9ZB373IBD#/224403223_Settings-_Discoveryl)

**Comment by vnylst** [comment]
![settings discovery](https://cloud.githubusercontent.com/assets/13191477/24493006/75a9b436-1557-11e7-83a8-1504242f80e1.png)
![settings app settings](https://cloud.githubusercontent.com/assets/13191477/24493012/798e30cc-1557-11e7-87bd-e1a2ad18bfff.png)
